=== danielgomezobraztsov/sisweb_cosas/sisweb2/JSONschema/profe/JSON_Schema/schemas/film.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "http://example.com/schemas/film.schema.json",
  "title": "Film",
  "description": "Film info",
  "type": "object",
  "properties":{
    "title": {"type": "string"},
    "sinopsis": {"type": "string"},
    "year": {
      "type": "integer",
      "minimum": 1888},
    "director": {
      "type": "string"
    },
    "directors": {
      "$ref": "#/$defs/personsArray"
    },
    "genres": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Action", "Adventure", "Animation", "Anime", "Comedy", "Documentary", "Drama", "Family", "Fantasy", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "Western"]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "certification": {
      "type": "string",
      "enum": ["R","G","PG","PG-13","NC-17"]
    },
    "rating": {
      "type": "number",
      "minimum": 0,
      "maximum": 10
    },
    "numRatings": {
      "type": "integer",
      "minimum": 0
    },
    "duration":  {
      "type": "integer",
      "minimum": 0
    },
    "stars":  {
      "$ref": "#/$defs/personsArray"
    }
  },
  "required": ["title", "year", "duration"],
  "oneOf": [
    { "required": ["director"]},
    { "required": ["directors"] }
  ],
  "$defs":{
    "personsArray": {
      "type": "array",
      "items": {"type": "string"},
      "minItems": 1,
      "uniqueItems": true
    }
  }
}

=== danielgomezobraztsov/sisweb_cosas/sisweb2/JSONschema/profe/JSON_Schema/schemas/hamnet.json
{
  "title": "Hamnet",
  "sinopsis": "After losing their son Hamnet to plague...",
  "year": 2025,
  "director": "Chloé Zhao",
  "genres": ["Drama", "Romance"],
  "certification": "PG-13",
  "rating": 7.9,
  "numRatings": 65000,
  "duration": 125,
  "stars": ["Jessie Buckley", "Paul Mescal", "Zac Wishart"]
}
