=== danielgomezobraztsov/sisweb_cosas/sisweb2/JSONschema/ej3/ej3Schema_Ver_profesor.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "http://example.com/schemas/film.schema.json",
  "title": "Film",
  "description": "Film info",
  "type": "object",
  "properties":{
    "title": {"type": "string"},
    "sinopsis": {"type": "string"},
    "year": {
      "type": "integer",
      "minimum": 1888},
    "directors": {
      "$ref": "#/$defs/personsArray"
    },
    "genres": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Action", "Sci-Fi"]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "certification": {
      "type": "string",
      "enum": ["R","G","PG","PG-13","NC-17"]
    },
    "rating": {
      "type": "number",
      "minimum": 0,
      "maximum": 10
    },
    "numRatings": {
      "type": "integer",
      "minimum": 0
    },
    "duration":  {
      "type": "integer",
      "minimum": 0
    },
    "stars":  {
      "$ref": "#/$defs/personsArray"
    }
  },
  "required": ["title", "year", "duration"],
  "$defs":{
    "personsArray": {
      "type": "array",
      "items": {"type": "string"},
      "minItems": 1,
      "uniqueItems": true
    }
  }
}

=== danielgomezobraztsov/sisweb_cosas/sisweb2/JSONschema/profe/JSON_Schema/schemas/the_matrix.json
{
  "title": "The Matrix",
  "sinopsis": "When a beautiful stranger leads computer hacker Neo...",
  "year": 1999,
  "directors": ["Lana Wachowski", "Lilly Wachowski"],
  "genres": ["Action", "Sci-Fi"],
  "certification": "R",
  "rating": 8.7,
  "numRatings": 2200000,
  "duration": 136,
  "stars": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
}
